require_relative 'square'

module SquareIndustry
  def initialize
    SpecialSquareFactory.build('Go')
    SquareFactory.build(:name     => 'Mediterranean Avenue',
                        :type     => 'purple',
                        :price    => 60,
                        :rent     => [2, 10, 30, 90, 160, 250],
                        :house    => 50,
                        :mortgage => 30)
    SpecialSquareFactory.build('Community Chest')
    SquareFactory.build(:name     => 'Baltic Avenue',
                        :type     => 'purple',
                        :price    => 60,
                        :rent     => [4, 20, 60, 180, 320, 450],
                        :house    => 50,
                        :mortgage => 30)
    SpecialSquareFactory.build('Income Tax')
    SquareFactory.build(:name     => 'Reading Railroad',
                        :type     => 'railroad',
                        :price    => 200,
                        :rent     => [25, 50, 100, 200],
                        :house    => 'none',
                        :mortgage => 100)
    SquareFactory.build(:name     => 'Oriental Avenue',
                        :type     => 'light blue',
                        :price    => 100,
                        :rent     => [6, 30, 90, 270, 400, 550],
                        :house    => 50,
                        :mortgage => 50)
    SpecialSquareFactory.build('Chance')
    SquareFactory.build(:name     => 'Vermont Avenue',
                        :type     => 'light blue',
                        :price    => 100,
                        :rent     => [6, 30, 90, 270, 400, 550],
                        :house    => 50,
                        :mortgage => 50)
    SquareFactory.build(:name     => 'Connecticut Avenue',
                        :type     => 'light blue',
                        :price    => 120,
                        :rent     => [8, 40, 100, 300, 450, 600],
                        :house    => 50,
                        :mortgage => 60)
    SpecialSquareFactory.build('Jail')
    SquareFactory.build(:name     => 'St. Charles Place',
                        :type     => 'pink',
                        :price    => 120,
                        :rent     => [10, 50, 150, 450, 625, 750],
                        :house    => 100,
                        :mortgage => 70)
    SquareFactory.build(:name     => 'Electric Company',
                        :type     => 'utility',
                        :price    => 150,
                        :rent     => 'depends on the roll',
                        :house    => 'none',
                        :mortgage => 75)
    SquareFactory.build(:name     => 'States Avenue',
                        :type     => 'pink',
                        :price    => 120,
                        :rent     => [10, 50, 150, 450, 625, 750],
                        :house    => 100,
                        :mortgage => 70)
    SquareFactory.build(:name     => 'Virginia Avenue',
                        :type     => 'pink',
                        :price    => 160,
                        :rent     => [12, 60, 180, 500, 700, 900],
                        :house    => 100,
                        :mortgage => 80)
    SquareFactory.build(:name     => 'Pennsylvania Railroad',
                        :type     => 'railroad',
                        :price    => 200,
                        :rent     => [25, 50, 100, 200],
                        :house    => 'none',
                        :mortgage => 100)
    SquareFactory.build(:name     => 'St. James Place',
                        :type     => 'orange',
                        :price    => 180,
                        :rent     => [14, 70, 200, 550, 750, 950],
                        :house    => 100,
                        :mortgage => 90)
    SpecialSquareFactory.build('Community Chest')
    SquareFactory.build(:name     => 'Tennessee Avenue',
                        :type     => 'orange',
                        :price    => 180,
                        :rent     => [14, 70, 200, 550, 750, 950],
                        :house    => 100,
                        :mortgage => 90)
#reformatted to here
    SquareFactory.build(       :name  =>  'New York Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'orange',
                               :price =>  200,
                               :rent  =>  [16, 80, 220, 600, 800, 1000],
                               :house =>  100,
                               :mortgage => 100,
                               :list  =>  @square_manifest)
    SpecialSquareFactory.build(:name  =>  'Free Parking',
                               :owner =>  'the Gamemaster',
                               :type  =>  'special',
                               :list  => @square_manifest)
    SquareFactory.build(       :name  =>  'Kentucky Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'red',
                               :price =>  220,
                               :rent  =>  [18, 90, 250, 700, 875, 1050],
                               :house =>  150,
                               :mortgage => 110,
                               :list  =>  @square_manifest)
    SpecialSquareFactory.build(:name  =>  'Chance',
                               :owner =>  'the Gamemaster',
                               :type  =>  'special',
                               :list  => @square_manifest)
    SquareFactory.build(       :name  =>  'Indiana Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'red',
                               :price =>  220,
                               :rent  =>  [18, 90, 250, 700, 875, 1050],
                               :house =>  150,
                               :mortgage => 110,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'Illinois Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'red',
                               :price =>  240,
                               :rent  =>  [20, 100, 300, 750, 925, 1100],
                               :house =>  150,
                               :mortgage => 120,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'B & O Railroad',
                               :owner =>  'the Bank',
                               :type  =>  'railroad',
                               :price =>  200,
                               :rent  =>  [25, 50, 100, 200],
                               :house =>  'none',
                               :mortgage => 100,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'Atlantic Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'yellow',
                               :price =>  260,
                               :rent  =>  [22, 110, 330, 800, 975, 1150],
                               :house =>  150,
                               :mortgage => 130,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'Ventnor Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'yellow',
                               :price =>  260,
                               :rent  =>  [22, 110, 330, 800, 975, 1150],
                               :house =>  150,
                               :mortgage => 130,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'Water Works',
                               :owner =>  'the Bank',
                               :type  =>  'utility',
                               :price =>  150,
                               :rent  =>  'depends on the roll',
                               :house =>  'none',
                               :mortgage => 75,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'Marvin Gardens',
                               :owner =>  'the Bank',
                               :type  =>  'yellow',
                               :price =>  280,
                               :rent  =>  [24, 120, 360, 850, 1025, 1200],
                               :house =>  150,
                               :mortgage => 140,
                               :list  =>  @square_manifest)
    SpecialSquareFactory.build(:name  =>  'Go to Jail',
                               :owner =>  'the Gamemaster',
                               :type  =>  'special',
                               :list  => @square_manifest)
    SquareFactory.build(       :name  =>  'Pacific Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'green',
                               :price =>  300,
                               :rent  =>  [26, 130, 390, 900, 1100, 1275],
                               :house =>  200,
                               :mortgage => 150,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'North Carolina Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'green',
                               :price =>  300,
                               :rent  =>  [26, 130, 390, 900, 1100, 1275],
                               :house =>  200,
                               :mortgage => 150,
                               :list  =>  @square_manifest)
    SpecialSquareFactory.build(:name  =>  'Community Chest',
                               :owner =>  'the Gamemaster',
                               :type  =>  'special',
                               :list  => @square_manifest)
    SquareFactory.build(       :name  =>  'Pennsylvania Avenue',
                               :owner =>  'the Bank',
                               :type  =>  'green',
                               :price =>  320,
                               :rent  =>  [28, 150, 450, 1000, 1200, 1400],
                               :house =>  200,
                               :mortgage => 160,
                               :list  =>  @square_manifest)
    SquareFactory.build(       :name  =>  'Shortline Railroad',
                               :owner =>  'the Bank',
                               :type  =>  'railroad',
                               :price =>  200,
                               :rent  =>  [25, 50, 100, 200],
                               :house =>  'none',
                               :mortgage => 100,
                               :list  =>  @square_manifest)
    SpecialSquareFactory.build(:name  =>  'Chance',
                               :owner =>  'the Gamemaster',
                               :type  =>  'special',
                               :list  => @square_manifest)
    SquareFactory.build(       :name  =>  'Park Place',
                               :owner =>  'the Bank',
                               :type  =>  'blue',
                               :price =>  300,
                               :rent  =>  [35, 175, 500, 1100, 1300, 1500],
                               :house =>  200,
                               :mortgage => 175,
                               :list  =>  @square_manifest)
    SpecialSquareFactory.build(:name  =>  'Luxury Tax',
                               :owner =>  'the Gamemaster',
                               :type  =>  'special',
                               :list  => @square_manifest)
    SquareFactory.build(       :name  =>  'Boardwalk',
                               :owner =>  'the Bank',
                               :type  =>  'blue',
                               :price =>  400,
                               :rent  =>  [50, 200, 600, 1400, 1700, 2000],
                               :house =>  200,
                               :mortgage => 200)
  end
end
